image: Visual Studio 2019

environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - npm test

on_success:
  - echo "Build successful!"
